#######################################################
# Database Configuration
# Connection string is in Go pq driver format:
# host=<host> port =<port> user=<databaseUser>
# password=<databaseUserrPassword> dbname=<databaseName>
[database]
connection_string = "host=localhost port=5432 user=postgres password=postgres dbname=runners_db sslmode=disable"
max_idle_connection = 5
max_open_connections = 20
connection_max_lifetime = "60s"
driver_name = "postgres"
#####################################################################
# HTTP Server configuration
[http]
server_address = ":8080"
#####################################################################
